### LOGIN ADMIN
POST http://127.0.0.1:3000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "1234"
}

### LOGIN USER
POST http://127.0.0.1:3000/login
Content-Type: application/json

{
  "username": "user",
  "password": "1234"
}

### GET ALL USERS
GET http://127.0.0.1:3000/api/users
Authorization: "31e58503-a879-435f-907a-9a6ddccccd35"

### GET SINGLE USER
GET http://127.0.0.1:3000/api/user/1
Authorization: "31e58503-a879-435f-907a-9a6ddccccd35"

### CREATE USER
POST http://127.0.0.1:3000/api/user
Content-Type: application/json
Authorization: "31e58503-a879-435f-907a-9a6ddccccd35"

{
  "username": "nuovoUser",
  "password": "1234",
  "role": "user"
}

### DELETE USER
DELETE http://127.0.0.1:3000/api/user/1
Authorization: "31e58503-a879-435f-907a-9a6ddccccd35"